# data
dataset: fmnist

# model
model_name: gar
baseline_path: /bigdata/f_mnist/logs/garipov/baselines/1647955843/gar_18_dNone_128_sgd_l0.1_g0.1_w0.0_sTrue/cnn_best.pth

# training
batch: 128
epochs: 10
optimizer: 'sgd'
momentum: 0.9
lr: 1.0e-4
gamma: 0
weight_decay: 0

# factorization
factorization: 'tt'
decompose_weights: true
rank: 20.07
layers:
- 6

# datalogging
data_dir: "/bigdata/f_mnist" 
logdir: "/bigdata/f_mnist/logs/garipov/decomposed" 

# hardware
data_workers: 8
