# data
dataset: cifar10

# model
model_name: rn18
baseline_path: /bigdata/cifar10/logs/baselines/1646668631/rn18_18_dNone_128_adam_l0.001_g0.1_w0.0_sTrue/cnn_best.pth

# training
batch: 128
epochs: 10
optimizer: 'adam'
lr: 1.0e-5
gamma: 0

# factorization
factorization: 'tucker'
decompose_weights: true
different_ranks: false
rank: 0.1
layers:
- 6
- 9
- 12
- 15
- 19
- 22
- 25
- 28
- 31
- 35
- 38
- 41
- 44
- 47
- 51
- 54
- 57
- 60
- 63

# datalogging
data_dir: "/bigdata/cifar10" 
logdir: "/bigdata/cifar10/logs/rn18/constant" 

# hardware
data_workers: 8
