baseline_path: /scratch/jetzeschuurman/f_mnist/logs/parn_18_d0.5_256_sgd_l0.1_g0.1_sTrue/1633280228/cnn_best
batch: 256
cpu: '2'
cuda: '3'
data_dir: /scratch/jetzeschuurman/f_mnist/data
data_workers: 2
decompose_weights: true
epochs: 25
factorization: cp
gamma: 0.9
layers:
- 5
- 7
- 11
- 13
- 18
- 20
- 25
- 27
- 32
- 34
- 39
- 41
- 46
- 48
- 53
- 55
logdir: /scratch/jetzeschuurman/f_mnist/logs
lr: 0.01
model_name: parn
rank: 0.75
