# data
dataset: cifar10

# model
model_name: gar

# training
batch: 128
epochs: 100
optimizer: 'sgd'
momentum: 0.9
lr: 1.0e-1
gamma: 0.1
milestones:
- 30
- 60
- 90
weight_decay: 0

# datalogging
data_dir: "/bigdata/cifar10" 
logdir: "/bigdata/cifar10/logs/garipov" 

# hardware
data_workers: 8
