tune: True

# model
model_name: parn
baseline_path: "/scratch/jetzeschuurman/f_mnist/logs/parn_18_d0.5_256_sgd_l0.1_g0.1_sTrue/1633280228/cnn_best"

# hparams
gamma:
- 0.1
- 0.5
- 0.9
- 1.
lr:
- 1.e-1
- 1.e-2
- 1.e-3
- 1.e-4
- 1.e-5
rank:
- 0.25
- 0.5
- 0.75
factorization:
- tucker
- cp
- tt
decompose_weights:
- 1
- 0

# tuning settings
max_epochs: 5
num_samples: 3
metric: 'accuracy'
mode: 'max'
grace_period: 2

# training
batch: 256
epochs: 200

# factorization
runtype: decompose
layers:
- 5
- 7
- 11
- 13
- 18
- 20
- 25
- 27
- 32
- 34
- 39
- 41
- 46
- 48
- 53
- 55

# datalogging
data_dir: "/scratch/jetzeschuurman/f_mnist/data" 
logdir: "/scratch/jetzeschuurman/f_mnist/logs" 
checkpoint_dir: "/scratch/jetzeschuurman/f_mnist/logs/"

#hardware
data_workers: 2
cuda: "1"
cpu: "2"
cpus_per_trial: 2
gpus_per_trial: 1
