# data
dataset: cifar10

# model
model_name: rn18
baseline_path: /bigdata/cifar10/logs/baselines/1646668631/rn18_18_dNone_128_adam_l0.001_g0.1_w0.0_sTrue/cnn_best.pth

# training
batch: 128
epochs: 25
optimizer: 'adam'
lr: 1.0e-5
gamma: 0

# factorization
factorization: 'tt'
decompose_weights: true
rank: 25.6
layers:
- 38

# datalogging
data_dir: "/bigdata/cifar10" 
logdir: "/bigdata/cifar10/logs/decomposed/tt" 

# hardware
data_workers: 8
